name: ci

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: gcc:16.1

    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Release
          - Debug

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Verify compiler
      run: g++ --version

    - name: Install dependencies
      run: apt-get -y update && apt-get -y install cmake libbenchmark-dev libboost-test-dev

    - name: Configure CMake
      run: cmake -B ./build --preset default -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

    - name: Build
      run: cmake --build ./build --config ${{matrix.build_type}}

    - name: Test
      run: ctest --test-dir ./build -C ${{matrix.build_type}}
